<a href="https://colab.research.google.com/github/mnfaizp/Big-Data-Course/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Understanding Data Type in Pythoh
Penyimpanan data pada pemrograman sangatlah perlu dan diperhatikan. Python memberikan kemudahan dengan Dynamic Typeing dimana tidak perlu mmelakukan inisialisi variable dengan tipe data yang sudah diketahui

In [ ]:
result = 0
for i in range(100):
  result += 1

In [ ]:
x = 4
x = "four"
x

'four'

##A Python Integer Is More Than Just an Integer
Pada python sebuah variable integer bukan hanyalah integer semata, namun merupakan sebuah objek yang diarahkan ke struktur. Sebuah integer pada Python 3.4 terdiri dari ob_refcnt, ob_type, ob_size, dan ob_digit

In [ ]:
"""
Struktur sebuah integer pada python yang 
dijelaskan menggunakan bahasa akarnya yakni C

struct __longobject {
    long ob_refcnt;         -> Akan membuat memori dan mengalikasikan object
    PyTypeObject *pb_type;  -> melakukan encode type variable
    size_t ob_size          -> mengambil ukuran
    long ob_digit[1]        -> memuat integer yang sebenarnya
}

"""

'\nStruktur sebuah integer pada python yang \ndijelaskan menggunakan bahasa akarnya yakni C\n\nstruct __longobject {\n    long ob_refcnt;         -> Akan membuat memori dan mengalikasikan object\n    PyTypeObject *pb_type;  -> melakukan encode type variable\n    size_t ob_size          -> mengambil ukuran\n    long ob_digit[1]        -> memuat integer yang sebenarnya\n}\n\n'

##A Python List is More Than Just a List
Pembuatan list pada python sangatlah mudah, dan begitu juga tipe data yang dikandungnya bisa heteerogen, namun hal ini dikarenakan setiap anggota pada list merupakan sebuah objek tunggal. Hal ini tentunya mengurangi efisiensi. 

In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(L[0])

int

In [ ]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
type(L2[0])

str

In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

##Fixed-Type Arrays in Python
Penggunaan list tentunya mengurangi efisiensi dalam menjalankan kode namun hal ini dapat diatasi dengan menggunakan array() yang telah disediakan python. Namun, array ini memiliki sebuah kekurangan dimana diperlukannya deklarasi tipe data. Hal tersebut diatasi oleh NumPy Array yang dapat membuat isi list array heterogen dan multidimensional

In [ ]:
import array 
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# import numpy as np
np.array([1, 3, 2, 5])

array([1, 3, 2, 5])

In [ ]:
np.array([3.14, 4, 2, 6])

array([3.14, 4.  , 2.  , 6.  ])

In [ ]:
# jika ingin hasil keluaran memiliki data type yang sama
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
# multidimensional array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

##Creating Array From Scratch

In [ ]:
# membuat array nol dnegan panjang 10
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# membuat matrik 3x5 dengan nilai 1
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# membuat array 3x5 dengan 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# membuat array dengan sequence number
# dimulai dari 0 diakhiri dengan 20, dengan interval 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# Membuat array dengan 5 nilai didisbrusikan secara merata antara 0 sampai 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Membuat array 3x3 secara terdistribusi
# niali random antara 0 sampai 1
np.random.random((3, 3))

array([[0.68023397, 0.21141777, 0.66022201],
       [0.36227647, 0.06265786, 0.29102762],
       [0.78450326, 0.37974164, 0.69774949]])

In [ ]:
#membuat array 3x3 notmal distribution
# dengan rerata 0 dan standar deviasi 1
np.random.normal(0, 1, (3, 3))

array([[-1.6939579 , -0.06215653,  0.69462925],
       [ 1.83590323,  0.43945017, -0.99507919],
       [-0.31651637, -0.65932813,  0.7511953 ]])

In [ ]:
# Membuat array 3x3 dengan niali random 
np.random.randint(0, 10, (3, 3))

array([[2, 4, 1],
       [6, 7, 6],
       [2, 4, 0]])

In [ ]:
# Membuat array identitas 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Membuat array kosong
np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types

In [ ]:
#dengan string
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
# dengan numpy
np.zeros(10, dtype=np.int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Basic of NumPy Arrays

## NumPy Array Attributes

In [ ]:
np.random.seed(0)  # seed untuk pembuatan dummy

x1 = np.random.randint(10, size=6)  # array satu dimensi
x2 = np.random.randint(10, size=(3, 4))  # array dua dimensi
x3 = np.random.randint(10, size=(3, 4, 5))  # array tiga dimensi

ndim merupakan jumlah dimensi, shape besar dari tiap dimensi, dan size merupakan besar array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


dtype dapat memperlihatkan tipe data dari seluruh array

In [ ]:
print("dtype:", x3.dtype)

dtype: int64


itemsize akan menampilkan besar dalam bytes tiap elemen array nya, dan nbytes akan menampilkan besar total

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


## Array Indexing: Accessing Single Elements

kita dapat mengakses dengan menggunakan nomor index

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

5

In [ ]:
x1[4]

7

In [ ]:
x1[-1]

9

In [ ]:
x1[-2]

7

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 0]

In [ ]:
x2[2, 0]

In [ ]:
x2[2, -1]

nilai dari array juga bisa diubah menggunakan index

In [ ]:
x2[0, 0] = 12
x2

## Array Slicing: Accessing Subarrays



kita juga bisa menggunakan [] untuk mengakses subarrays. Hal tersebut dapat dilakukan menggunakan :

In [ ]:
x[start:stop:step]

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x